#!/usr/bin/env python3
"""PreToolUse guard for hear-embed: protect vendored code, secrets, and the lockfile.

Reads the hook JSON on stdin and *denies* a tool call that would violate a
documented project invariant (see CLAUDE.md). Wired up in .claude/settings.json
on the ``Edit|MultiEdit|Write|NotebookEdit|Read`` matcher. Stdlib-only so it runs
under a bare ``python3`` with no venv/torch — fast enough to fire on every call.

Deny rules:
  * write under hear_embed/_vendor/  -> vendored, unmodified
  * read/write of .env / .env.*      -> secrets (HF_TOKEN); gitignored
  * write of uv.lock                 -> machine-generated by `uv lock`

Anything else is allowed. Exit 0 with no output = allow.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# .claude/hooks/guard_paths.py -> parents[2] is the project root, regardless of cwd.
# resolve() the guarded paths so a symlinked _vendor/uv.lock still matches the
# resolved target below.
ROOT = Path(__file__).resolve().parents[2]
VENDOR_DIR = (ROOT / "hear_embed" / "_vendor").resolve()
LOCK_FILE = (ROOT / "uv.lock").resolve()

# Every tool that can mutate a file. Kept broad on purpose: a Claude Code build
# that exposes another edit tool (e.g. MultiEdit) must not silently bypass a guard.
WRITE_TOOLS = {"Edit", "MultiEdit", "Write", "NotebookEdit"}
READ_TOOLS = {"Read"}


def _is_env_secret(path: Path) -> bool:
    """True for a dotenv secret file: ``.env`` / ``.env.*`` but not ``.env.example``.

    Matches by basename like ``.gitignore``'s ``.env`` / ``.env.*`` family, so a
    secret in any directory (``.env.local``, ``config/.env``) is covered.
    """
    name = path.name
    if name == ".env.example":
        return False
    return name == ".env" or name.startswith(".env.")


def _deny(reason: str) -> None:
    """Emit a PreToolUse deny decision and exit."""
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    sys.exit(0)


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)  # unparseable payload -> never block

    tool = data.get("tool_name", "")
    tool_input = data.get("tool_input") or {}
    fp = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not fp:
        sys.exit(0)

    raw = Path(fp)
    if not raw.is_absolute():
        raw = Path.cwd() / raw
    target = raw.resolve()  # follow symlinks so a link into _vendor/.env is caught

    # 1. Google's audio_utils.py is vendored unmodified; never edit/lint/reformat it.
    if tool in WRITE_TOOLS and target.is_relative_to(VENDOR_DIR):
        _deny(
            f"{target.name} is under hear_embed/_vendor/, vendored unmodified from "
            "Google-Health/hear (Apache-2.0). CLAUDE.md marks it a hard invariant: "
            "never edit, lint, or reformat it. Blocked."
        )

    # 2. .env / .env.* hold secrets (HF_TOKEN) and are gitignored. Keep them out of
    #    edits and transcripts; .env.example stays allowed. Check the name the tool
    #    used *and* the symlink-resolved name.
    if (tool in WRITE_TOOLS or tool in READ_TOOLS) and (
        _is_env_secret(raw) or _is_env_secret(target)
    ):
        _deny(
            f"{raw.name} is a dotenv secret file (holds e.g. HF_TOKEN) and is "
            "gitignored. Reading or writing it here risks leaking secrets into the "
            "transcript. Use .env.example for the template, or handle secrets "
            "outside Claude. Blocked."
        )

    # 3. uv.lock is generated by uv; regenerate via `uv lock`, never hand-edit.
    if tool in WRITE_TOOLS and target == LOCK_FILE:
        _deny(
            "uv.lock is generated by uv and must not be hand-edited. Change deps in "
            "pyproject.toml and run `uv lock` (or `uv sync`) instead. Blocked."
        )

    sys.exit(0)  # allow


if __name__ == "__main__":
    main()
