#!/usr/bin/env python3
"""PreToolUse guard for hear-embed: protect vendored code, secrets, and the lockfile.

Reads the hook JSON on stdin and *denies* a tool call that would violate a
documented project invariant (see CLAUDE.md). Wired up in .claude/settings.json
on the ``Edit|Write|NotebookEdit|Read`` matcher. Stdlib-only so it runs under a
bare ``python3`` with no venv/torch — fast enough to fire on every matched call.

Deny rules:
  * Edit/Write/NotebookEdit under hear_embed/_vendor/  -> vendored, unmodified
  * Read/Edit/Write of .env                            -> holds HF_TOKEN; gitignored
  * Edit/Write of uv.lock                              -> machine-generated by `uv lock`

Anything else is allowed. Exit 0 with no output = allow.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# .claude/hooks/guard_paths.py -> parents[2] is the project root, regardless of cwd.
ROOT = Path(__file__).resolve().parents[2]
VENDOR_DIR = ROOT / "hear_embed" / "_vendor"
ENV_FILE = ROOT / ".env"
LOCK_FILE = ROOT / "uv.lock"

WRITE_TOOLS = {"Edit", "Write", "NotebookEdit"}
READ_TOOLS = {"Read"}


def _is_within(child: Path, parent: Path) -> bool:
    """True if ``child`` is ``parent`` or lives beneath it (works pre-3.9)."""
    try:
        child.relative_to(parent)
        return True
    except ValueError:
        return False


def _deny(reason: str) -> None:
    """Emit a PreToolUse deny decision and exit."""
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": reason,
                }
            }
        )
    )
    sys.exit(0)


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)  # unparseable payload -> never block

    tool = data.get("tool_name", "")
    tool_input = data.get("tool_input") or {}
    fp = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not fp:
        sys.exit(0)

    target = Path(fp)
    if not target.is_absolute():
        target = Path.cwd() / target
    target = target.resolve()

    # 1. Google's audio_utils.py is vendored unmodified; never edit/lint/reformat it.
    if tool in WRITE_TOOLS and _is_within(target, VENDOR_DIR):
        _deny(
            f"{target.name} is under hear_embed/_vendor/, vendored unmodified from "
            "Google-Health/hear (Apache-2.0). CLAUDE.md marks it a hard invariant: "
            "never edit, lint, or reformat it. Blocked."
        )

    # 2. .env holds secrets (HF_TOKEN) and is gitignored. Keep it out of edits and
    #    transcripts; .env.example (a different path) stays allowed.
    if target == ENV_FILE and (tool in WRITE_TOOLS or tool in READ_TOOLS):
        _deny(
            ".env holds secrets (HF_TOKEN) and is gitignored. Reading or writing it "
            "here risks leaking the token into the transcript. Use .env.example for "
            "the template, or handle the secret outside Claude. Blocked."
        )

    # 3. uv.lock is generated by uv; regenerate via `uv lock`, never hand-edit.
    if tool in WRITE_TOOLS and target == LOCK_FILE:
        _deny(
            "uv.lock is generated by uv and must not be hand-edited. Change deps in "
            "pyproject.toml and run `uv lock` (or `uv sync`) instead. Blocked."
        )

    sys.exit(0)  # allow


if __name__ == "__main__":
    main()
